const { Book } = require("../models/Book.js");

const bookList = [
  { title: "The Lost Symphony", author: "Madeleine Guyonneau", pages: 980, publisher: "Whimsical Press" },
  { title: "The Midnight Symphony", author: "Rachelle Sproat", pages: 98, publisher: "Fantasy Books Co." },
  { title: "The Secret Symphony", author: "Olin Gai", pages: 700, publisher: "Enchanted Editions" },
  { title: "The Silver Symphony", author: "Mina MacKean", pages: 936, publisher: "Novelty Books Inc." },
  { title: "The Hidden Symphony", author: "Merilee Ashbridge", pages: 956, publisher: "Make-Believe Publishers" },
  { title: "Whispers in the Wind", author: "Leena Lewsey", pages: 909, publisher: "Enchanted Editions" },
  { title: "The Lost City", author: "Raf Florey", pages: 370, publisher: "Enchanted Editions" },
  { title: "Lost in Time", author: "Sumner Scrancher", pages: 868, publisher: "Imaginary House" },
  { title: "The Hidden Path", author: "Bianka Harrison", pages: 820, publisher: "Dreamscape Publishing" },
  { title: "The Crimson Symphony", author: "Jessamine Didsbury", pages: 149, publisher: "Enchanted Editions" },
  { title: "The Forgotten Kingdom", author: "Tallulah Derl", pages: 196, publisher: "Whimsical Press" },
  { title: "The Emerald Isle", author: "Harcourt Stapells", pages: 602, publisher: "Storyteller Publications" },
  { title: "Whispers of the Heart", author: "Paulo Plumridege", pages: 820, publisher: "Dreamscape Publishing" },
  { title: "The Hidden Symphony", author: "Hersch Thornham", pages: 736, publisher: "Fantasy Books Co." },
  { title: "The Starlight Symphony", author: "Gabey Sowle", pages: 955, publisher: "Fantasy Books Co." },
  { title: "The Midnight Sonata", author: "Venita Hubery", pages: 399, publisher: "Storyteller Publications" },
  { title: "The Midnight Sonata", author: "Adan Clavey", pages: 522, publisher: "Fictional Press" },
  { title: "Lost in Time", author: "Jourdan Dorward", pages: 212, publisher: "Bookworm Publishing" },
  { title: "The Hidden Treasure", author: "Gwyn Stokoe", pages: 271, publisher: "Bookworm Publishing" },
  { title: "The Starlight Symphony", author: "Ally Andriolli", pages: 674, publisher: "Make-Believe Publishers" },
  { title: "The Enchanted Symphony", author: "Jacquelynn Foxton", pages: 588, publisher: "Fantasy Books Co." },
  { title: "The Emerald Symphony", author: "Vassily Bellison", pages: 267, publisher: "Fictional Press" },
  { title: "The Midnight Symphony", author: "Catha Braybrooke", pages: 562, publisher: "Novelty Books Inc." },
  { title: "The Silver Lining", author: "Lorne Tregenna", pages: 207, publisher: "Fictional Press" },
  { title: "The Secret Symphony", author: "Kennith Diment", pages: 471, publisher: "Novelty Books Inc." },
  { title: "The Golden Symphony", author: "Clarisse Pasmore", pages: 58, publisher: "Imaginary House" },
  { title: "The Hidden Symphony", author: "Zorana Ruddom", pages: 922, publisher: "Make-Believe Publishers" },
  { title: "Whispers in the Wind", author: "Tedda Rowell", pages: 831, publisher: "Fictional Press" },
  { title: "A Tale of Two Cities", author: "Willi Andriuzzi", pages: 390, publisher: "Bookworm Publishing" },
  { title: "The Crystal Key", author: "Yorker Campany", pages: 957, publisher: "Whimsical Press" },
  { title: "The Midnight Sonata", author: "Bobby Rawcliffe", pages: 395, publisher: "Whimsical Press" },
  { title: "The Crimson Symphony", author: "Deerdre Huc", pages: 910, publisher: "Novelty Books Inc." },
  { title: "The Midnight Symphony", author: "Louie Eastmead", pages: 507, publisher: "Fantasy Books Co." },
  { title: "The Starlight Symphony", author: "Elizabet Sacaze", pages: 800, publisher: "Make-Believe Publishers" },
  { title: "The Hidden Symphony", author: "Ronny Sandifer", pages: 570, publisher: "Imaginary House" },
  { title: "The Hidden Symphony", author: "Venita Doerr", pages: 794, publisher: "Fictional Press" },
  { title: "The Silver Symphony", author: "Anastasia Bunyan", pages: 966, publisher: "Whimsical Press" },
  { title: "The Starlight Symphony", author: "Tessie Udall", pages: 317, publisher: "Enchanted Editions" },
  { title: "Whispers in the Wind", author: "Stacy Dannell", pages: 438, publisher: "Novelty Books Inc." },
  { title: "The Lost Symphony", author: "Dena Cressor", pages: 731, publisher: "Fictional Press" },
  { title: "The Forgotten Symphony", author: "Kaleb Hateley", pages: 401, publisher: "Dreamscape Publishing" },
  { title: "The Crimson Symphony", author: "Raquela Wandrich", pages: 392, publisher: "Whimsical Press" },
  { title: "The Secret Symphony", author: "Jemima Shapira", pages: 214, publisher: "Bookworm Publishing" },
  { title: "The Hidden Symphony", author: "Giffy Clemont", pages: 728, publisher: "Imaginary House" },
  { title: "The Midnight Masquerade", author: "Izak Langrish", pages: 656, publisher: "Storyteller Publications" },
  { title: "The Crystal Key", author: "Antone Aveline", pages: 773, publisher: "Enchanted Editions" },
  { title: "The Crimson Symphony", author: "Avrom Spiers", pages: 163, publisher: "Fantasy Books Co." },
  { title: "The Enchanted Symphony", author: "Jocko Semken", pages: 97, publisher: "Imaginary House" },
  { title: "The Golden Compass", author: "Celestyn Cooke", pages: 409, publisher: "Imaginary House" },
  { title: "Whispers in the Wind", author: "Sheela Philippe", pages: 360, publisher: "Imaginary House" },
  { title: "The Golden Gate", author: "Rosaline Rushmere", pages: 795, publisher: "Enchanted Editions" },
  { title: "The Crimson Symphony", author: "Euell Springham", pages: 998, publisher: "Bookworm Publishing" },
  { title: "The Forgotten Realm", author: "Amara Ismead", pages: 704, publisher: "Dreamscape Publishing" },
  { title: "The Hidden Symphony", author: "Jedd Hessel", pages: 535, publisher: "Novelty Books Inc." },
  { title: "The Crimson Symphony", author: "Alair Gladwin", pages: 981, publisher: "Make-Believe Publishers" },
  { title: "The Hidden Treasure", author: "Artus Soro", pages: 57, publisher: "Dreamscape Publishing" },
  { title: "The Last Voyage", author: "Saw Weber", pages: 487, publisher: "Novelty Books Inc." },
  { title: "The Golden Symphony", author: "Kathryn Stollenwerck", pages: 539, publisher: "Novelty Books Inc." },
  { title: "The Lost Symphony", author: "Eleanore Eckels", pages: 787, publisher: "Enchanted Editions" },
  { title: "The Emerald Isle", author: "Pierre Ferrarello", pages: 449, publisher: "Whimsical Press" },
  { title: "The Forgotten Symphony", author: "Vladamir Lancastle", pages: 333, publisher: "Dreamscape Publishing" },
  { title: "The Golden Symphony", author: "Xever Christauffour", pages: 64, publisher: "Storyteller Publications" },
  { title: "The Emerald Symphony", author: "Krystalle Lenham", pages: 233, publisher: "Dreamscape Publishing" },
  { title: "The Secret Symphony", author: "Konstanze Spawton", pages: 730, publisher: "Whimsical Press" },
  { title: "The Crimson Symphony", author: "Abba Harverson", pages: 492, publisher: "Fictional Press" },
  { title: "The Forgotten Symphony", author: "Keary Golsthorp", pages: 935, publisher: "Novelty Books Inc." },
  { title: "The Silver Lining", author: "Ranee Antonognoli", pages: 475, publisher: "Storyteller Publications" },
  { title: "The Golden Symphony", author: "Kelsey McClymond", pages: 205, publisher: "Storyteller Publications" },
  { title: "The Enchanted Mirror", author: "Skip Roseborough", pages: 646, publisher: "Make-Believe Publishers" },
  { title: "The Crimson Symphony", author: "Gaelan MacIntosh", pages: 602, publisher: "Enchanted Editions" },
  { title: "The Forgotten Symphony", author: "Malvin Smalridge", pages: 430, publisher: "Novelty Books Inc." },
  { title: "The Midnight Symphony", author: "Bili Lydiate", pages: 854, publisher: "Enchanted Editions" },
  { title: "A Tale of Two Cities", author: "Bev Postance", pages: 625, publisher: "Novelty Books Inc." },
  { title: "The Starlight Chronicles", author: "Fernandina Goodchild", pages: 966, publisher: "Fantasy Books Co." },
  { title: "The Forgotten Symphony", author: "Kristian Dedon", pages: 388, publisher: "Bookworm Publishing" },
  { title: "The Lost City", author: "Franklyn Dooly", pages: 374, publisher: "Storyteller Publications" },
  { title: "The Lost Symphony", author: "Rickard Rubbert", pages: 264, publisher: "Make-Believe Publishers" },
  { title: "The Starlight Symphony", author: "Cecile Hankard", pages: 365, publisher: "Bookworm Publishing" },
  { title: "The Forgotten Realm", author: "Morgan Manterfield", pages: 709, publisher: "Storyteller Publications" },
  { title: "The Hidden Path", author: "Gabriello Mansuer", pages: 432, publisher: "Fantasy Books Co." },
  { title: "The Lost Symphony", author: "Fidelity Knowlys", pages: 576, publisher: "Dreamscape Publishing" },
  { title: "The Hidden Symphony", author: "Chris Agnolo", pages: 146, publisher: "Fictional Press" },
  { title: "The Forgotten Realm", author: "Nat Soda", pages: 603, publisher: "Dreamscape Publishing" },
  { title: "The Lost Symphony", author: "Karim Copperwaite", pages: 865, publisher: "Whimsical Press" },
  { title: "The Silver Symphony", author: "Far Bedell", pages: 308, publisher: "Dreamscape Publishing" },
  { title: "The Secret Symphony", author: "Buckie Yair", pages: 822, publisher: "Novelty Books Inc." },
  { title: "The Enchanted Forest", author: "Jada Stump", pages: 802, publisher: "Enchanted Editions" },
  { title: "The Secret Keeper", author: "Pace Fortoun", pages: 987, publisher: "Imaginary House" },
  { title: "The Hidden Symphony", author: "Minny Pohlke", pages: 284, publisher: "Fictional Press" },
  { title: "The Silver Sword", author: "Meyer Pitceathly", pages: 314, publisher: "Imaginary House" },
  { title: "The Secret Symphony", author: "Steffi Banting", pages: 843, publisher: "Make-Believe Publishers" },
  { title: "The Secret Garden", author: "Adria Pfaffel", pages: 927, publisher: "Dreamscape Publishing" },
  { title: "The Golden Symphony", author: "Clovis Gawkroge", pages: 574, publisher: "Storyteller Publications" },
  { title: "The Crystal Key", author: "Beryl Di Meo", pages: 496, publisher: "Whimsical Press" },
  { title: "The Silver Symphony", author: "Kirk Ramsay", pages: 596, publisher: "Dreamscape Publishing" },
  { title: "The Golden Symphony", author: "Tadd Gillicuddy", pages: 62, publisher: "Enchanted Editions" },
  { title: "The Forgotten Kingdom", author: "Torre Mc Giffin", pages: 308, publisher: "Dreamscape Publishing" },
  { title: "The Enchanted Symphony", author: "Emmaline Battman", pages: 950, publisher: "Imaginary House" },
  { title: "The Emerald City", author: "Frederich Reveley", pages: 454, publisher: "Make-Believe Publishers" },
  { title: "The Golden Compass", author: "Rayna McColm", pages: 755, publisher: "Enchanted Editions" },
];

const bookSeed = async () => {
  // Borrar datos
  await Book.collection.drop();
  console.log("Deleted books");

  // Añadimos libros
  const documents = bookList.map((book) => new Book(book));
  await Book.insertMany(documents);
  console.log("Datos guardados correctamente");

  return documents;
};

module.exports = { bookSeed };
